name: phise
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - matplotlib=3.10.3
  - astropy=7.1.0
  - scipy=1.16.0
  - ipywidgets=8.1.7
  - sympy=1.14.0
  - numba=0.61.2
  - nbformat=5.10.4
  - gitpython=3.1.44
  - pip=25.1.1
  - pandas=2.3.0
  - jupyterlab
  - ipykernel
  - notebook
  - pip:
    - LRFutils==0.1.2
    - fitter==1.7.1
    - toml

# End of environment.yml
